title = "Rayworks"

gitSourceBranch = "master"
changelog = true
classOrder = []

[home]
enabled = true

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

[footer]
style = "dark"
copyright = "Copyright © 2024 ilililliliilililililiili. Built with Moonwave and Docusaurus"